GET https://golden-whispering-show.glitch.me

###

POST https://golden-whispering-show.glitch.me 
Content-Type: application/json

{
"image": "https://pagrindinis.barbora.lt/api/images/GetInventoryImage?id=d0fb9982-06e1-469d-ae79-e7efd69c59a1",
"title": "Gerimanto Varske", "price": 5.99
}